[sidebar] Including Sidebar Library in Repository
CESARBR/angular-libraries pull request #3
Opened 2021-08-27 15:58 UTC by rpao

- The sidebar must work as a template where can be added content to the header, body, and footer.
- A server controls the sidebars' actions, including opening and closing, using the sidebar's id.
- The main UI/UX designs are the same as the original code.

2021-08-27 20:30 UTC, rodrigoperazzo commented on projects/lib-sidebar/package.json
> +    "@angular/common": "^11.0.9",
Can we try to make the library compatible with Angular versions from 8+?

2021-08-27 20:44 UTC, CGSILVA requested changes

2021-08-27 20:44 UTC, CGSILVA commented on projects/lib-sidebar/src/lib/service/lib-sidebar.service.ts
> +  public add(sidebar: any): boolean {
Please create a type for siderbar

2021-08-27 20:44 UTC, CGSILVA commented on projects/lib-sidebar/README.md
> +This library was generated with [Angular CLI](https://github.com/angular/angular-cli) version 11.0.9.
If you change Angular version remember to change here

2021-09-20 09:02 UTC, rpao commented on projects/lib-sidebar/src/lib/service/lib-sidebar.service.ts
> +  public add(sidebar: any): boolean {
The sidebar receives an instance of LibSidebarComponent, so it was defined as type LibSidebarComponent.

2021-09-20 09:07 UTC, rpao commented on projects/lib-sidebar/README.md
> +This library was generated with [Angular CLI](https://github.com/angular/angular-cli) version 11.0.9.
Done.

2021-09-20 09:09 UTC, rpao commented on projects/lib-sidebar/package.json
> +    "@angular/common": "^11.0.9",
Angular Version is now the same as the Tooltip Directive.

2021-09-22 12:59 UTC, merged